name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alterest-todos" #Must be unique in Heroku
          heroku_email: "saurabhdutta.jk@gmail.com"
          usedocker: true
        env:
          ROOT_URL: https://alterest-todos.herokuapp.com
          MONGO_URL: "mongodb+srv://meteor:${{secrets.MONGO_METEOR_PASS}}@cluster0.sli2u.mongodb.net/meteor"
          MONGO_OPLOG_URL: "mongodb+srv://meteor:${{secrets.MONGO_METEOR_PASS}}@cluster0.sli2u.mongodb.net/local"
          PORT: 3000