name: Build and Deploy

on:
  push:
    branches:
      - master

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: "alterest-todos"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      - name: Publish # Push the Docker image to Heroku Container Registry
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
